# Generated by Django 3.2.8 on 2021-10-25 07:46

from django.db import migrations, models
import nlg_slider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=nlg_slider.models.change_name2, verbose_name='عکس')),
            ],
        ),
    ]
