# Generated by Django 3.2.8 on 2021-10-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلایدر '},
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان عکس'),
        ),
    ]
