# Generated by Django 3.2.8 on 2021-10-11 13:55

from django.db import migrations, models
import nlg_article.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=nlg_article.models.change_name2)),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال ')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
    ]
