# Generated by Django 3.2.8 on 2021-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(),
        ),
    ]
