# Generated by Django 3.2.8 on 2021-10-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_article', '0002_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
