# Generated by Django 3.2.8 on 2021-10-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_article', '0004_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Commnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('message', models.TextField()),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nlg_article.article')),
            ],
        ),
    ]
