# Generated by Django 3.2.8 on 2021-10-25 07:38

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import nlg_article.models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_category', '0004_auto_20211025_1108'),
        ('nlg_article', '0009_alter_article_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='article_commnet',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='reply_commnet',
            options={'verbose_name': 'ریپلای کامنت', 'verbose_name_plural': ' ریپلای کامنت ها '},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=120, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, to='nlg_category.Category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nlg_article.models.change_name2, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='article_commnet',
            name='allowed',
            field=models.BooleanField(default=False, verbose_name='مجاز'),
        ),
        migrations.AlterField(
            model_name='article_commnet',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='article_commnet',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='article_commnet',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام '),
        ),
        migrations.AlterField(
            model_name='reply_commnet',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nlg_article.article_commnet', verbose_name='کامنت'),
        ),
        migrations.AlterField(
            model_name='reply_commnet',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='ایمیل '),
        ),
        migrations.AlterField(
            model_name='reply_commnet',
            name='message',
            field=models.TextField(verbose_name='پیام '),
        ),
        migrations.AlterField(
            model_name='reply_commnet',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
    ]
