# Generated by Django 3.2.8 on 2021-10-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_article', '0010_auto_20211025_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply_commnet',
            name='allowed',
            field=models.BooleanField(default=False, verbose_name='مجاز'),
        ),
    ]
