# Generated by Django 3.2.8 on 2021-10-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_tag', '0002_remove_tag_articles'),
        ('nlg_article', '0011_reply_commnet_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='nlg_tag.Tag', verbose_name='مقاله'),
        ),
    ]
