# Generated by Django 3.2.8 on 2021-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال ')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
