# Generated by Django 3.2.8 on 2021-10-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_category', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
