# Generated by Django 3.2.8 on 2021-10-25 07:38

from django.db import migrations, models
import nlg_category.models


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_category', '0003_category_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی ', 'verbose_name_plural': ' دسته بندی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='مورد علاقه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=nlg_category.models.change_name2, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=120, verbose_name='عنوان'),
        ),
    ]
