# Generated by Django 3.2.8 on 2021-10-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlg_tag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
    ]
